# Generated by Django 5.1.1 on 2024-09-20 03:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_interest_userinterest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
